name: restore
description: 'restore dependencies'
inputs:
  token:
    required: true
    description: 'GitHub token'

runs:
  using: composite
  steps:
  - uses: actions/setup-node@v4
    name: caching
    with:
      node-version: 21
      cache: pnpm
      cache-dependency-path: pnpm-lock.yaml
    
  - name: installing deps
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.token }}
    run: |
      pnpm i --frozen-lockfile
  