name: 'Create release' 
description: 'Creates a new release'
inputs:
  token:
    required: true
    description: 'GitHub token'
  owner: 
    required: true
    description: 'Owner of repository'
  repository:
    required: true
    description: 'Repository name'
  
  
  tag_name:
    required: true
    description: 'The name of the tag.'
  target_commitish:
    description: | 
      Specifies the commitish value that determines where the 
      Git tag is created from. Can be any branch or commit SHA. 
      Unused if the Git tag already exists. 
      Default: the repository's default branch.
  name:
    description: 'The name of the release.'
  body:
    description: 'Text describing the contents of the tag.'
  draft:
    description: |
      true to create a draft (unpublished) release, false to create a published one.
      Default: false
  prerelease:
    description: |
      true to identify the release as a prerelease. false to identify the release as a full release.
      Default: false
  discussion_category_name:
    description: |
      If specified, a discussion of the specified category is created and linked to the release. 
      The value must be a category that already exists in the repository.
  generate_release_notes:
    description: |
      Whether to automatically generate the name and body for this release. 
      If name is specified, the specified name will be used; otherwise, 
      a name will be automatically generated. 
      If body is specified, the body will be pre-pended to the automatically generated notes.
      Default: false
  make_latest:
    description: |
      Specifies whether this release should be set as the latest release for the repository. 
      Drafts and prereleases cannot be set as latest. 
      Defaults to true for newly published releases. 
      legacy specifies that the latest release should be determined based on the 
      release creation date and higher semantic version.
      Default: true
      Can be one of: true, false, legacy

outputs:
  id:
    description: 'The id of created release'
  url:
    description: 'The url of created release'
  upload_url:
    description: 'The upload_url of created release'

runs:
  using: node20
  main: dist/index.js
